### ISSUE TITLE
Aria Lables

### ISSUE THREAD

**Issue by erynjones** [erynjones/dsn1675-saas-website#5]
For aria labels are we supposed to just label the link that read the main or everything? For example i labeled all the sign-up buttons for the pricing page by saying which option your signing up for. Would i need to label everything on the home page like the sign-up button, take a tour, and pricing or not because they are already different?
@thomasjbradley

**Comment by thomasjbradley** [comment]
You're right, you only need to add the `aria-label` if the text inside the `<a>` tags, the text visible on the screen, is all the same. The idea being that if your user uses VoiceOver the links can be distinguished by ARIA label if the text inside the links is all the same.
